import dash
from dash.dependencies import Input, Output
import dash_core_components as dcc
import dash_html_components as html
from datetime import datetime as dt
from flask import Flask, request, redirect
import re
import os
import pymongo

server = Flask(__name__)

app = dash.Dash(__name__,url_base_pathname='/release-history/',server=server)
#app.config.supress_callback_exceptions=True  #It is set to suppress the exception that is generated while assigning callbacks to components that are not in the initial layout but are generated by other callbacks
#server = app.server
app.css.config.serve_locally = True
app.scripts.config.serve_locally = True
app.config['suppress_callback_exceptions'] = True
